# Generated by Django 5.2.dev20241008103955 on 2024-11-17 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isFiction',
            new_name='is_fiction',
        ),
    ]
